[workspace]
authors = ["Riccardo Sacco <riccardo.sacco@usi.ch>", "R. Kalvitis <r.kalvitis@usi.ch>"]
channels = ["robostack-staging", "conda-forge"]
name = "robotics-final-ws"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
# ROS2 Humble
python = "==3.10.13"
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
compilers = ">=1.7.0,<2"
make = ">=4.4.1,<5"

# CoppeliaSim dependencies
cbor2 = ">=5.6.5,<6"
pyzmq = ">=26.2.0,<27"

# robomaster_sim dependencies
spdlog = ">=1.11.0,<2"
boost = ">=1.78.0,<2"
cmake = ">=3.26.3,<4"
ffmpeg = ">=5.1.2,<6"
libxslt = ">=1.1.37,<2"
xmlschema = ">=3.4.5,<4"

# RoboMasterSDK dependencies
libopus = ">=1.4,<2"

# robomaster_ros dependencies
ros-humble-xacro = ">=2.0.8,<3"
ros-humble-launch-xml = ">=1.0.4,<2"
ros-humble-cv-bridge = ">=3.2.1,<4"
ros-humble-launch-testing-ament-cmake = ">=1.0.4,<2"
ros-humble-robot-state-publisher = ">=3.0.2,<4"
ros-humble-joint-state-publisher = ">=2.3.0,<3"
ros-humble-joint-state-publisher-gui = ">=2.3.0,<3"
ros-humble-joy = ">=3.1.0,<4"

# robomaster_example dependencies
transforms3d = ">=0.4.2,<0.5"

[pypi-dependencies]
# RoboMasterSDK
robomaster = { git = "https://github.com/EliaCereda/RoboMaster-SDK.git", branch = "patch-2" }
libmedia_codec = { git = "https://github.com/EliaCereda/RoboMaster-SDK.git", branch = "patch-2", subdirectory = "lib/libmedia_codec"}

# robomaster_ros dependencies
numpy-quaternion = ">=2024.0.8, <2025"

[activation]
scripts = ["install/setup.sh"]

[activation.env]
ROS_LOCALHOST_ONLY="1"

COPPELIASIM_ROOT_DIR="/Applications/coppeliaSim.app/Contents/Resources"

# CMake toolchain file to use only Pixi libraries in the build process
CMAKE_TOOLCHAIN_FILE="$PIXI_PROJECT_ROOT/pixi-toolchain.cmake"

[target.osx-64.tasks]
coppelia = "$COPPELIASIM_ROOT_DIR/../MacOS/coppeliaSim"

[target.osx-arm64.tasks]
coppelia = "$COPPELIASIM_ROOT_DIR/../MacOS/coppeliaSim"

[target.linux-64.tasks]
coppelia = "$COPPELIASIM_ROOT_DIR/coppeliaSim.sh"
